### ISSUE TITLE
Modular

### ISSUE THREAD

**Issue by CleverSource** [AmaranthineCodices/roact-material#5]
This is not modular enough, on checkmarks, switchs, etc we need power to check their state.

Ex:
Switch:checkState()
--This will return true if the Checked is true, false if Checked is false
--and then we can do 
if Switch:checkState == true then
-- make text appear, etc
end

**Comment by AmaranthineCodices** [comment]
This is not how Roact is designed; you should not be checking child component states - you shouldn't even be in a position to use the API you propose.

Roact is derived heavily from [React](https://reactjs.org/), and shares most of that ecosystem's paradigms. One of the core principles of React is that *state flows downhill*. It does not flow uphill. If I have a structure like this:

* SomeComponent
  * Checkbox

SomeComponent is not allowed to check the state of the Checkbox. The checkbox is the sole owner of its state; nothing else may interact with it.

There's an article on this in React's docs called [Thinking in React](https://reactjs.org/docs/thinking-in-react.html). It shows how parent components respond to changes in their children's states: through event listeners. These don't exist right now, but they will in the future!
